### PR TITLE
Remove stray end of comment block

### PR DESCRIPTION
**Pull request by remyabel**
Fixes a small syntax error.

### CODE REVIEW

**Comment by erose1337** [comment]
@remyabel Thanks a lot! 

May I ask how you found this?

**Comment by remyabel** [comment]
Found what? The error? The good ol' fashioned way by viewing the source in the browser and seeing red tags.

**Comment by erose1337** [comment]
Yep! I was just curious, I was wondering if reading the source files on random github repos was a hobby or something. I don't exactly get a lot of pull requests, and I was most surprised to see one for my github pages repo.

**Comment by remyabel** [comment]
The entire chain of events was:

- Saw your Hot Network Question
- Went to your profile
- Went to your site
- Viewed site in browser (I always do this because I'm curious to see what kind of shenanigans is going on like using obsolete DOCTYPEs)
- Found your Github
- Opened a PR for something that doesn't even affect the rendering of the page

But yes, Github does actually kind of encourage you to make PR's to random repos via its trending repo/issue label system.

**Comment by erose1337** [comment]
Oh cool! Thanks for entertaining my curiosity, and I appreciate you taking the time to do so.

**Pull request merged**
